        $meals = [
            // Available Meals (10)
            [
                'name' => 'Buffalo Wings',
                'description' => 'Crispy chicken wings tossed in spicy buffalo sauce',
                'price' => 12.99,
                'category_id' => $appetizers->id,
                'is_available' => true,
            ],
            [
                'name' => 'Grilled Salmon',
                'description' => 'Fresh Atlantic salmon grilled to perfection with lemon herb butter',
                'price' => 24.99,
                'category_id' => $mainCourses->id,
                'is_available' => true,
            ],
            [
                'name' => 'Beef Steak',
                'description' => 'Premium ribeye steak cooked to your preference',
                'price' => 32.99,
                'category_id' => $mainCourses->id,
                'is_available' => true,
            ],
            [
                'name' => 'Spaghetti Carbonara',
                'description' => 'Classic Italian pasta with eggs, cheese, and pancetta',
                'price' => 17.99,
                'category_id' => $pasta->id,
                'is_available' => true,
            ],
            [
                'name' => 'Margherita Pizza',
                'description' => 'Classic pizza with tomato sauce, mozzarella, and basil',
                'price' => 16.99,
                'category_id' => $pizza->id,
                'is_available' => true,
            ],
            [
                'name' => 'Caesar Salad',
                'description' => 'Fresh romaine lettuce with caesar dressing and croutons',
                'price' => 11.99,
                'category_id' => $salads->id,
                'is_available' => true,
            ],
            [
                'name' => 'Tomato Basil Soup',
                'description' => 'Creamy tomato soup with fresh basil',
                'price' => 8.99,
                'category_id' => $soups->id,
                'is_available' => true,
            ],
            [
                'name' => 'Chocolate Cake',
                'description' => 'Rich chocolate cake with chocolate ganache',
                'price' => 7.99,
                'category_id' => $desserts->id,
                'is_available' => true,
            ],
            [
                'name' => 'Fresh Orange Juice',
                'description' => 'Freshly squeezed orange juice',
                'price' => 4.99,
                'category_id' => $beverages->id,
                'is_available' => true,
            ],
            [
                'name' => 'Coffee',
                'description' => 'Freshly brewed coffee',
                'price' => 2.99,
                'category_id' => $beverages->id,
                'is_available' => true,
            ],

            // Unavailable Meals (5)
            [
                'name' => 'Mozzarella Sticks',
                'description' => 'Golden fried mozzarella cheese sticks with marinara sauce',
                'price' => 9.99,
                'category_id' => $appetizers->id,
                'is_available' => false,
            ],
            [
                'name' => 'Chicken Parmesan',
                'description' => 'Breaded chicken breast with marinara sauce and melted mozzarella',
                'price' => 18.99,
                'category_id' => $mainCourses->id,
                'is_available' => false,
            ],
            [
                'name' => 'Pepperoni Pizza',
                'description' => 'Traditional pizza topped with pepperoni and mozzarella',
                'price' => 18.99,
                'category_id' => $pizza->id,
                'is_available' => false,
            ],
            [
                'name' => 'Tiramisu',
                'description' => 'Classic Italian dessert with coffee and mascarpone',
                'price' => 8.99,
                'category_id' => $desserts->id,
                'is_available' => false,
            ],
            [
                'name' => 'Iced Tea',
                'description' => 'Refreshing iced tea with lemon',
                'price' => 3.99,
                'category_id' => $beverages->id,
                'is_available' => false,
            ],
        ];
